apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myapp"
  namespace: "inspica"
spec:
  selector:
    matchLabels:
      app: "myapp"
  replicas: 3
  template:
    metadata:
      labels:
        app: "myapp"
    spec:
      containers:
      - image: public.ecr.aws/m7s1f3q1/inspica:latest
        imagePullPolicy: Always
        name: "myapp"
        ports:
        - containerPort: 80
          protocol: TCP
