apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: production
  labels:
     platform: fargate
     app: nginx
spec:
  containers:
  - name: nginx
    image: 126279675365.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
